DROP TABLE IF EXISTS
    seats CASCADE;

DROP TABLE IF EXISTS
    actions CASCADE;

DROP TYPE IF EXISTS
    player_action CASCADE;

DROP TYPE IF EXISTS
    phase CASCADE;

DROP TABLE IF EXISTS
    cards CASCADE;

DROP TYPE IF EXISTS
    deal_to CASCADE;

DROP TYPE IF EXISTS
    card_suit CASCADE;

DROP TABLE IF EXISTS
    hands CASCADE;

DROP TABLE IF EXISTS
    players CASCADE;

DROP TABLE IF EXISTS
    games CASCADE;
